language: java

git:
  quiet: false
  
before_install:
  - gradle installWrapper
  
jobs:
  include:
  - jdk: openjdk8
    os: linux
  - jdk: openjdk11
    os: linux
  - jdk: openjdk11
    os: osx
  allow_failures:
  - os: osx
script: gradlew buildCore
script: gradlew buildUI

Notifications:
  email:
    recipients:
    - diehl@uni-trier.de
    on_success: never
    on_failure: always //change
